# Generated by Django 3.1.4 on 2021-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='content',
            field=models.CharField(default='no content now', max_length=10000),
        ),
    ]
