# Generated by Django 3.1.4 on 2021-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_poster_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
